title: <p align="center"> Dhananjay Buva</p>
logo: /assets/img/logo.png
description: Data enthusiast, Quality Manager - Manual & automation functional testing, security testing , performance testing, Agile Coach and DevOp manager
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
